package com.bluedart.manageparcelshoppodusers.dao;

import java.util.ArrayList;

import org.springframework.web.bind.annotation.PathVariable;

import com.bluedart.manageparcelshoppodusers.dto.ManageParcelShopPODUsersAuditDto;
import com.bluedart.manageparcelshoppodusers.dto.ManageParcelShopPODUsersDto;
import com.bluedart.manageparcelshoppodusers.dto.ManageParcelShopPODUsersNotificationsDto;
import com.bluedart.manageparcelshoppodusers.dto.ParcelShopPODUsersDetailsDto;
import com.bluedart.manageparcelshoppodusers.dto.ParcelShopPODUsersSearchDto;
import com.bluedart.manageparcelshoppodusers.dto.ParcelShopPODUsersSearchResultDto;

public interface ManageParcelShopPODUsersDao {

	public ManageParcelShopPODUsersDto getParcelShopsList(String region,String area,String searchParcelShopName);
	public ManageParcelShopPODUsersDto getServiceCentersList(String region,String area,String searchServiceCenterCode,String searchServiceCenterName);
	public ManageParcelShopPODUsersDto createParcelShopPODUser(ParcelShopPODUsersDetailsDto parcelShopPODUsersDetailsDto);
	public ManageParcelShopPODUsersDto getParcelShopPODUserDetails(String loginId,ArrayList<String> region,String podStatus);
	public ManageParcelShopPODUsersDto deactivateParcelShopPODUser(ParcelShopPODUsersSearchResultDto parcelShopPODUsersSearchResultDto);
	public ManageParcelShopPODUsersDto reactivateParcelShopPODUser(ParcelShopPODUsersSearchResultDto parcelShopPODUsersSearchResultDto);
	public ManageParcelShopPODUsersDto getParcelShopPODUsers(ParcelShopPODUsersSearchDto parcelShopPODUsersSearchDto);
	public ManageParcelShopPODUsersDto updateParcelShopPODUser(ParcelShopPODUsersDetailsDto parcelShopPODUsersDetailsDto);
	public ManageParcelShopPODUsersDto getAreaRegionList(ArrayList<String> region);
	public ManageParcelShopPODUsersAuditDto manageParcelShopPODUsersSaveAuditLogDetails(ManageParcelShopPODUsersAuditDto manageParcelShopPODUsersAuditDto);
	public ManageParcelShopPODUsersAuditDto deleteAuditLog(ArrayList<String> auditSequenceList);
	public String sendEmailManageParcelShopPODUser(ManageParcelShopPODUsersNotificationsDto manageParcelShopPODUsersNotificationsDto);

}
